# Generated by Django 2.1.7 on 2019-06-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('room', models.IntegerField()),
                ('room_in', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('thr', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
