# Generated by Django 2.1.7 on 2019-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='smoke',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
