# Generated by Django 2.1.7 on 2019-06-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_roomate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roomate',
        ),
        migrations.AddField(
            model_name='post',
            name='pattern',
            field=models.CharField(default='AA', max_length=20),
        ),
    ]
